--1
select nombre, apellido1, apellido2 from PROFESORES where departamento = 1;

--2
select nombre, apellido1, apellido2 from PROFESORES where departamento != 3;

--3
select nombre, apellido1, apellido2 from profesores where upper(email) like '%LCC.UMA.ES';

--4
select * from alumnos where email is null;

--5
SELECT NOMBRE,
        CREDITOS, 
        (TEORICOS/CREDITOS)*100 AS "TEORICOS (%)", 
        (PRACTICOS/CREDITOS)*100 AS "PRACTICOS (%)"
FROM ASIGNATURAS WHERE CURSO = 3;

--6
SELECT ALUMNO, CALIFICACION FROM MATRICULAR WHERE ASIGNATURA = 112 ORDER BY ALUMNO;

--7
SELECT NOMBRE, (HOMBRES+MUJERES) AS "POBLACION" FROM MUNICIPIO;

--8
SELECT DECODE(GENERO, 'MASC', 'El alumno ', 'La alumna ') || NOMBRE || ' ' || APELLIDO1 ||
' ' || APELLIDO2 || ' no tiene Correo' as "Correos" from alumnos where email is null;

--9
SELECT NOMBRE, APELLIDO1, APELLIDO2 FROM PROFESORES WHERE TO_DATE('01/01/1990', 'DD/MM/YYYY') > ANTIGUEDAD;

--10
SELECT NOMBRE, APELLIDO1, APELLIDO2 FROM PROFESORES WHERE MONTHS_BETWEEN(SYSDATE, FECHA_NACIMIENTO)/12 < 40;

--11
SELECT UPPER(NOMBRE) AS "NOMBRE", UPPER(APELLIDO1) AS "APELLIDO1", UPPER(APELLIDO2) AS "APELLIDO2", TRUNC((MONTHS_BETWEEN(SYSDATE, ANTIGUEDAD)/12)/3) as "TRIENIOS"
FROM PROFESORES
WHERE TRUNC((MONTHS_BETWEEN(SYSDATE, ANTIGUEDAD)/12)) >= 9;

--12
SELECT UPPER(REPLACE(NOMBRE, 'Bases de Datos', 'Almacenes de Datos')) AS "NOMBRE" FROM ASIGNATURAS WHERE UPPER(NOMBRE) LIKE '%BASES DE DATOS%';

--13
SELECT NOMBRE, NVL(TO_CHAR(CREDITOS), 'NO ASIGNADO') AS "CREDITOS"  FROM ASIGNATURAS WHERE CARACTER LIKE 'O_';

--14
SELECT * FROM ALUMNOS WHERE MONTHS_BETWEEN(SYSDATE, FECHA_PRIM_MATRICULA) < 2;

--15
SELECT * FROM ALUMNOS WHERE MONTHS_BETWEEN(FECHA_PRIM_MATRICULA, FECHA_NACIMIENTO)/12 <18;

--16
SELECT * FROM ALUMNOS WHERE TO_CHAR(FECHA_PRIM_MATRICULA, 'DAY') LIKE '%MONDAY%' OR TO_CHAR(FECHA_PRIM_MATRICULA, 'DAY') LIKE '%LUNES%';

