/*    */ package net.agsh.towerdefense;
/*    */ 
/*    */ 
/*    */ public enum Parameter
/*    */ {
/*  6 */   GAME_STEP_SIZE, OBSTACLE_RADIUS_MIN, OBSTACLE_RADIUS_MAX, OBSTACLE_DENSITY, TOWER_RADIUS_MIN, TOWER_RADIUS_MAX,
/*  7 */   TOWER_RANGE_MIN, TOWER_RANGE_MAX, TOWER_DAMAGE_MIN, TOWER_DAMAGE_MAX, TOWER_COOLDOWN_MIN, TOWER_COOLDOWN_MAX,
/*  8 */   TOWER_DISPERSION_MIN, TOWER_DISPERSION_MAX, TOWER_COST_MIN, TOWER_COST_MAX, ENEMY_RADIUS_MIN, ENEMY_RADIUS_MAX,
/*  9 */   ENEMY_SPEED_MIN, ENEMY_SPEED_MAX, MAP_SIZE_X, MAP_SIZE_Y, MAP_GRID_SPACE, TOWER_MIN_MONEY_FACTOR,
/* 10 */   TOWER_MAX_MONEY_FACTOR, TOWER_DENSITY, ENEMY_HEALTH_MIN, ENEMY_HEALTH_MAX, ENEMY_SPAWN_INTERVAL, ENEMY_DENSITY,
/* 11 */   ENEMY_DENSITY_ROUND_FACTOR, GAME_MAX_ROUNDS, DEBUG_PRINT_TOWER_DETAILS, GUI, GUI_REFRESH_RATE,
/* 12 */   MAP_ENDING_POINTS, MAP_STARTING_POINTS, MAP_STARTING_POINTS_SEPARATION_FACTOR, MAP_ENDING_POINTS_SEPARATION_FACTOR, MAP_NODE_VALUES, OBSTACLE_MAX_TRIES;
/*    */ }


/* Location:              /home/miguel/Universidad/segundo/ADA/practicas/grupoTarde/PracticaTarde3/towerdefense.jar!/net/agsh/towerdefense/Config$Parameter.class
 * Java compiler version: 20 (64.0)
 * JD-Core Version:       1.1.3
 */