.PHONY: build build-async

build:
	gcc -Wall -o P1_echo_server P1_echo_server.c
	gcc -Wall -o P1_echo_client P1_echo_client.c

async:
	gcc -Wall -o P1_echo_server P1_echo_server_async.c
	gcc -Wall -o P1_echo_client P1_echo_client.c
