services:
  api:
    build: .
    ports:
      - "4000:80"
    environment:
      - REDIS_HOST=redis
    networks:
      - webnet

  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"
    networks:
      - webnet

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=redis-datasource
    volumes:
      - ./grafana_data:/var/lib/grafana
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
